### ISSUE TITLE
PIN authenticate not working

### ISSUE THREAD

**Issue by kispee** [normen/homebridge-bravia#109] opened 2020-06-06 10:36 UTC
It is not working to me.
My Sony Bravia TV shows the picture with PIN code, I am writing the PIN code in chrome (http://.... :8999) and it's nothing happens. 
I see the homebridge logs that:
[2020-6-6 12:24:36] [BraviaPlatform] Need to authenticate with TV!
[2020-6-6 12:24:36] [BraviaPlatform] Please enter the PIN that appears on your TV at http://i5-4460:11111
[2020-6-6 12:24:36] [BraviaPlatform] PIN entry web server listening

If I send the PIN again, the log refresh another same text.
I try the homebridge a Windows 10 PC, all firewall rules off.
I try another port (e.g: 11111), another browser (edge)
I try the TV restart.  (Sony KD-43XF596)

Please, what is  the solution?

**Comment by normen** [comment] 2020-06-06 14:00
No idea, maybe chrome tries to load https instead of http?

**Comment by kispee** [comment] 2020-06-06 14:27
Not working.
But I installed a previous version (2.1.0), it accepts the PIN code.
Interesting..

**Comment by normen** [comment] 2020-06-06 14:34
> But I installed a previous version (2.1.0), it accepts the PIN code.

The only thing that changed there is that the plugin now writes the entered pin back to the browser instead of just closing the connection. Did you try another browser?

**Comment by kispee** [comment] 2020-06-06 21:10
I tried explorer, but it is not working .
I installed every version until 2.1.8 version, all of them are working.

**Comment by normen** [comment] 2020-06-06 21:30
What do you mean by "working"? Do you mean you can enter a new PIN with those? Because the versions before 2.1.9 were always using the same uuid for the same name. Meaning if you named your TV the same then the plugin was "known" by your TV already and you didn't have to enter a PIN at all. From 2.1.9 on each new HomeKit-TV gets a new uuid and will trigger a new PIN request from your TV.

Another thing is to check the list of authorized "applications" in your TV. The plugin should be listed somewhere in your TV, theres a list of everything that had successfully enter a PIN.

**Comment by kispee** [comment] 2020-06-06 21:36
yes, I can enter the PIN and the TV respones, that my remote is successfully added.
I installed 2.1.9 version and also it is working. 
Okay, what you wrote , that I hardly understand. :) 
I hope, I could help finding the solution.

**Closed as completed** 2020-06-06 21:43 UTC

**Comment by B0LT5S** [comment] 2020-10-13 06:50
I'm still having the same issue, and downgrading from the latest version to 2.1.9 didn't change anything either, am I doing anything wrong?

**Comment by normen** [comment] 2020-10-13 11:41
Try a different browser

**Comment by B0LT5S** [comment] 2020-10-13 21:10
I tried using chrome instead of safari and the same issue happened.

**Comment by normen** [comment] 2020-10-14 10:38
No idea then, I can't reproduce the issue.
